### ISSUE TITLE
improve structure of config.yml

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/CEON#106]
The current structure of `config.yml` is not very suitable for managing multiple ontology versions, since there is both a lot of redundancy and it's difficult to get a good overview. A better alternative would be to use a nested structure where only the version numbers are updated. E.g.:
```yml
ontologies:
  actor:
    source: "ontology/modules/actor/"
    target: "ontology/actor/"
    versions:
      - 0.1
      - 0.2
  actorODP:
    source: "ontology/modules/actorODP"
    target: "ontology/actorODP/"
    versions:
      - 0.1
      - 0.2
```
